-- Generated by TypescriptToLua v0.1.3
-- https://github.com/Perryvw/TypescriptToLua
require("typescript_lualib")
local exports = exports or {}
local Unit = Unit or {}
exports.Unit = Unit
Unit.__index = Unit
function Unit.new(construct, ...)
    local instance = setmetatable({}, Unit)
    if construct and Unit.constructor then Unit.constructor(instance, ...) end
    return instance
end
function Unit.constructor(self)
    self.rotationRadius = 100
    self.phase = 0
    self.startPos = vmath.vector3()
    self.id = nil
end
function Unit.update(self,dt)
    if self.id==nil then
        return
    end
    self.phase=self.phase+dt
    local pos = vmath.vector3(self.startPos)

    pos.x=pos.x+(math.cos(self.phase)*self.rotationRadius)
    pos.y=pos.y+(math.sin(self.phase)*self.rotationRadius)
    pos.x=math.ceil(pos.x)
    pos.y=math.ceil(pos.y)
    go.set_position(pos,self.id)
end
function Unit.create(self)
    self.phase=math.random()
    self.startPos.x=math.random(200,800)
    self.startPos.y=math.random(200,500)
    self.startPos.z=0
    self.id=factory.create("/main#factory")
end
return exports
